// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATXBs_5x4qjPjzmO52LtiCPu6aEhDTcwA',
    appId: '1:238993311824:web:becc42f1608eab7051e955',
    messagingSenderId: '238993311824',
    projectId: 'electronic-dukan-6952d',
    authDomain: 'electronic-dukan-6952d.firebaseapp.com',
    storageBucket: 'electronic-dukan-6952d.firebasestorage.app',
    measurementId: 'G-DG7FQXKBDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqZ4YJ3XTZTDulhxy3Yu7sC3QgLZ-bDMk',
    appId: '1:238993311824:android:a572d91a7477d48451e955',
    messagingSenderId: '238993311824',
    projectId: 'electronic-dukan-6952d',
    storageBucket: 'electronic-dukan-6952d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD2pFcHvLIZOPcxsfku1nG7jLD41Hx6a4',
    appId: '1:238993311824:ios:06a80ee598db1eef51e955',
    messagingSenderId: '238993311824',
    projectId: 'electronic-dukan-6952d',
    storageBucket: 'electronic-dukan-6952d.firebasestorage.app',
    androidClientId: '238993311824-flucrl6v07qkeo7pgtn2pfr7gmt3g0af.apps.googleusercontent.com',
    iosClientId: '238993311824-6a2r8ekpai3lnsa8jb9egi8qg4p871q9.apps.googleusercontent.com',
    iosBundleId: 'com.example.alamStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD2pFcHvLIZOPcxsfku1nG7jLD41Hx6a4',
    appId: '1:238993311824:ios:06a80ee598db1eef51e955',
    messagingSenderId: '238993311824',
    projectId: 'electronic-dukan-6952d',
    storageBucket: 'electronic-dukan-6952d.firebasestorage.app',
    androidClientId: '238993311824-flucrl6v07qkeo7pgtn2pfr7gmt3g0af.apps.googleusercontent.com',
    iosClientId: '238993311824-6a2r8ekpai3lnsa8jb9egi8qg4p871q9.apps.googleusercontent.com',
    iosBundleId: 'com.example.alamStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATXBs_5x4qjPjzmO52LtiCPu6aEhDTcwA',
    appId: '1:238993311824:web:1746339babcc678451e955',
    messagingSenderId: '238993311824',
    projectId: 'electronic-dukan-6952d',
    authDomain: 'electronic-dukan-6952d.firebaseapp.com',
    storageBucket: 'electronic-dukan-6952d.firebasestorage.app',
    measurementId: 'G-E115YZKNTE',
  );

}